apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: kourosh-nginx
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: kourosh-nginx
    spec:
      containers:
      - name: nginx
        image: nginx
